version: '3'

services:
  app:
    image: node:8.10-alpine
    volumes:
      - ./:/var/www:cached
    ports:
      - 3000:3000
    working_dir: /var/www
    command: yarn start
    environment:
      REACT_APP_API_HOST: http://localhost:3000
