version: '3'

services:
  app:
    image: node:13-alpine
    volumes:
      - ./:/app:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:cached
      - $SSH_AUTH_SOCK:/ssh-agent:cached
    ports: [3000:3000]
    working_dir: /app
    command: yarn start
    environment:
      REACT_APP_API_HOST: http://localhost:3000
      SSH_AUTH_SOCK: /ssh-agent
